### PR TITLE
Contract error metadata collection and lint tool.

### PR DESCRIPTION
**Pull request by pyglot**
This commit adds a `teia_sc.error_collection` module which allows an option
to collect error metadata. The main use is to encapsulate tests and
methods related to producing consistent and compliant TZIP-16 error
metadata.

The first commit implements an example in daoToken only:
```
TARGET=daoToken make test
```
Results in `output/tests/daoToken/Lint_FAILWITH_messages/log.html`,
and in contract metadata under "errors", e.g. see Metdata tab in `output/tests/daoToken/Test_set_metadata/log.html`

The code has not been linted yet, but might be ok to take a look at now, at a high level.

### CODE REVIEW

**Comment by pyglot** [comment]
I am thinking I might see if I can decorate some of the smartpy functions, such as sp.verify() rather than 'collecting' the errors with the ERR() helper function. If it is possible to do that update to smartpy from outside of the smartpy module, I think it's a better way of collecting the error messages.

**Comment by pyglot** [comment]
There is an issue that became obvious in more complex scenarios with multiple contracts. So this is not in a useable state yet.

**Comment by pyglot** [comment]
This is working for me now. Time for a quick review, @jagracar. 

I am not sure if this should be taken in, or if it will cause a bit of clutter. I am fine with it being put on hold or directed elsewhere. 

The end product is a way to track most smart contract errors (providing the error-generating methods get triggered during test execution). It will then check what metadata is pre-recorded and see if it matches up to execution and if it looks 'compliant'. I have no deep understanding of TZIP-16, so don't trust my code on what it says is compliant!

There are no requirements and I tested with Python 3.8. 

My own thoughts include:
 - I believe the provided functionality is not necessary right now (nice to have but might cause a tiny bit of clutter), if more support for error metadata is desired later it can be taken in then. The same goes for multi-language support. That can be added later. 
 - So far I added the error_collection functionality to DAOToken and DAOGovernance targets only. 
 - The injection into smartpy works to find errors, but it might be missing some cases,  so it should perhaps be used in conjunction with a coverage tool to check that all relevant calls are executed. 
 - and it is of course dependent on smartpy not changing interfaces. When a smart contract is nearly ready for publication,  the injection can be removed and the constants can be used although the report discovery . 
 - I am not sure about the module name `teia_sc` or if it should even belong inside the same repository.

**Review by jagracar — APPROVED** [review]

**Comment by jagracar** [comment]
Looks good! Let me know if you want to merge it.

**Comment by jagracar** [comment]
The main problem i see is that one cannot copy paste the contracts to the smartpy gui and compile them. One will need to remove the import and the couple of lines involved, but it's not a big issue.

**Comment by pyglot** [comment]
There's still an issue with reading/setting up metadata when the contract is initialized with the metadata from ipfs function. Basically the input doesn't make too much sense. I think it will be an easier fix to accept it, but I didn't have time to look at it in any detail, yet.

**Comment by jagracar** [comment]
Merged!

**Pull request merged**
